newline_style = "Unix"
imports_layout = "Vertical"
fn_args_layout = "Vertical"
imports_granularity = "Item"
use_try_shorthand = true
max_width = 200
single_line_if_else_max_width = 200
use_small_heuristics = "Max"
match_block_trailing_comma = true
trailing_comma  = "Vertical"
use_field_init_shorthand = true
reorder_impl_items = true
format_code_in_doc_comments = true
merge_derives = true
