
# GENERATED: This file is automatically updated by 'Bump dependencies', local changes will be overwritten!

name: 'Test & lint'

on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  checks:
    name: Test & lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Read config
        run: |
          echo "STRICT=$([ "$(jq '.test_lint' -r ci-conf.json)" != false ] && [ "$(jq '.test_lint.lint_strict' -r ci-conf.json)" != false ] && echo 1 || echo 0)" | tee -a $GITHUB_ENV
          echo "TEST=$([ "$(jq '.test_lint' -r ci-conf.json)" != false ] && [ "$(jq '.test_lint.test' -r ci-conf.json)" != false ] && echo 1 || echo 0)" | tee -a $GITHUB_ENV
          echo "LINT=$([ "$(jq '.test_lint' -r ci-conf.json)" != false ] && [ "$(jq '.test_lint.lint' -r ci-conf.json)" != false ] && echo 1 || echo 0)" | tee -a $GITHUB_ENV
          echo "FMT=$([ "$(jq '.test_lint' -r ci-conf.json)" != false ] && [ "$(jq '.test_lint.fmt' -r ci-conf.json)" != false ] && echo 1 || echo 0)" | tee -a $GITHUB_ENV
      - name: Run test, lint, fmt
        uses: docker/build-push-action@v2
        with:
          file: ./ci/test-lint.Dockerfile
          context: .
          build-args: |
            STRICT=${{ STRICT }}
            TEST=${{ TEST }}
            LINT=${{ LINT }}
            FMT=${{ FMT }}
          push: false
